version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 29572:5672
      - 29672:15672 #guest:guest
    networks:
      - applications-networks

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - rabbitmq
    volumes:
      - $PWD/prometheus:/etc/prometheus
    networks:
      - applications-networks

  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - applications-networks

networks:
  applications-networks:
    name: applications-networks
