version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 29572:5672
      - 29672:15672 #guest:guest
    networks:
      - applications-networks

  rabbitmq-1:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    restart: always
    ports:
      - 29573:5672
      - 29673:15672 #guest:guest
    networks:
      - applications-networks
    volumes:
      - ./.erlang.cookie:/etc/rabbitmq/.erlang.cookie

  rabbitmq-2:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    restart: always
    ports:
      - 29574:5672
      - 29674:15672 #guest:guest
    networks:
      - applications-networks
    volumes:
      - ./.erlang.cookie:/etc/rabbitmq/.erlang.cookie

  rabbitmq-3:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=DSDSDSDSDSDSDJHBDHBHSDVHSVDSDDBSHSBDHJSD
    ports:
      - 29575:5672
      - 29675:15672 #guest:guest
    networks:
      - applications-networks
    volumes:
      - ./.erlang.cookie:/etc/rabbitmq/.erlang.cookie

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - rabbitmq
    volumes:
      - $PWD/prometheus:/etc/prometheus
    networks:
      - applications-networks

  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  applications-networks:
    name: applications-networks
