version: '3.8'
services:
  rabbitmq-monitor:
    image: rabbitmq:3.9.25-management-alpine
    container_name: rabbitmq-monitor
    restart: always
    ports:
      - 29572:5672
      - 29672:15672 #guest:guest
      - 29772:15692
    networks:
      - applications-networks-monitor

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus:/etc/prometheus
    networks:
      - applications-networks-monitor

  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - applications-networks-monitor

networks:
  applications-networks-monitor:
    name: applications-networks-monitor
