global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: rabbitmq-monitor
    static_configs:
      - targets:
          - rabbitmq-monitor:15692
    metrics_path: /metrics
